name: brew pr-pull

on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"
      
      - name: Add Signed-off-by lines
        run: |
          git rebase --exec "git commit --amend --no-edit -m \"\$(git show -s --format='%B%nSigned-off-by: %cn <%ce>')\"" origin/main

      - name: Pre-push commits to pass DCO checks
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git branch --copy main "$BRANCH--pre-push"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin "$BRANCH--pre-push"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          git push --delete origin "$BRANCH"
          git push --delete origin "$BRANCH--pre-push"
